### ISSUE TITLE
[Suggestion] Add ability to specify zombies from other mods in config.

### ISSUE THREAD

**Issue by offbeat-stuff** [offbeat-stuff/Zombie-Apocalypse#4]
I am currently thinking something like 

```toml
[Spawn.kind]
ids = ["minecraft:zombie","minecraft:husk","minecraft:zombie_villager","minecraft:drowned"]
weights = [100]
extraWeights = 30
conditions = ["air","desert","air","water"]
```

I have not yet decided on the conditions.
The default namespace for ids will be minecraft.

So husk can be `husk` but burned from [Rotten Creatures](https://modrinth.com/mod/rottencreatures) need to be `rottencreatures:burned`.

I will not be creating seperated lists based on unique conditions. Conditions will be checked after a mob is selected.

I may do a config settings based on different conditions where a mob is chosen based on certain conditions.

```toml
[Spawn.water]
chance = 0.1
discardIfNotChosen = true
id = "drowned"
```
