### ISSUE TITLE
[Suggestion] Simplify Config file. Especially lists of numbers.

### ISSUE THREAD

**Issue by offbeat-stuff** [offbeat-stuff/Zombie-Apocalypse#6]
Current config file
<details><summary>Config file</summary>

```toml
zombiesBurnInSunlight = false
doScream = true

[spawn]
spawnInstantly = false
vanillaSpawnRestrictionOnFoot = true
checkIfBlockBelowAllowsSpawning = true
lightLevel = 15
mobIds = ["zombie", "zombie_villager"]
minPlayerDistance = 16.0
maxZombieCount = 150
allowedDimensions = ["overworld", "the_nether", "the_end"]

[spawn.instantSpawning]
maxSpawnAttemptsPerTick = 100
maxSpawnsPerTick = 10

[spawn.mobWeights]
weights = [100, 5]
weightsForExtraEntries = 100

[spawn.variants]
chance = 0.01
frostWeight = 1
flameWeight = 1

[spawn.axisSpawnParameters]
chance = 0.1
min = 16
max = 48

[spawn.planeSpawnParameters]
chance = 0.1
min = 16
max = 48

[spawn.boxSpawnParameters]
chance = 0.1
min = 24
max = 64

[spawn.timeRange]
min = 1000
max = 13000

[Armor]
helmets = ["netherite", "diamond", "iron", "gold", "chainmail", "leather", "turtle"]
chestplates = ["netherite", "diamond", "iron", "gold", "chainmail", "leather"]
leggings = ["netherite", "diamond", "iron", "gold", "chainmail", "leather"]
boots = ["netherite", "diamond", "iron", "gold", "chainmail", "leather"]

[Armor.chancesPerSlot]
chances = [0.1, 0.1, 0.1, 0.1]
defaultChance = 0.1

[Armor.materialWeights]
weights = [1, 10, 100, 50, 50, 100]
weightsForExtraEntries = 10

[Weapon]
swords = ["netherite", "diamond", "iron", "gold", "stone", "wood"]
shovels = ["netherite", "diamond", "iron", "gold", "stone", "wood"]
pickaxes = ["netherite", "diamond", "iron", "gold", "stone", "wood"]
axes = ["netherite", "diamond", "iron", "gold", "stone", "wood"]
hoes = ["netherite", "diamond", "iron", "gold", "stone", "wood"]
chance = 0.1

[Weapon.weightsForTools]
weights = [100, 20, 20, 75, 1]
weightsForExtraEntries = 100

[Weapon.commonWeights]
weights = [1, 10, 100, 50, 50, 100]
weightsForExtraEntries = 100

[ArmorTrims]
patterns = ["sentry", "dune", "coast", "wild", "ward", "eye", "vex", "tide", "snout", "rib", "spire"]
materials = ["quartz", "iron", "netherite", "redstone", "copper", "gold", "emerald", "diamond", "lapis", "amethyst"]
vanillaOnly = true
chance = 0.1

[ArmorTrims.patternsWeights]
weights = []
weightsForExtraEntries = 110

[ArmorTrims.materialsWeights]
weights = [100, 100, 1, 50, 100, 100, 100, 10, 100, 100]
weightsForExtraEntries = 100

[enchantmentLevelRange]
min = 5
max = 40

[statusEffects]
effects = ["speed", "haste", "strength", "jump_boost", "regeneration", "resistance", "fire_resistance", "water_breathing", "invisibility", "health_boost", "absorption", "saturation", "slow_falling", "conduit_power", "dolphins_grace"]
maxTimeInTicks = -1
incrementalChances = [0.1, 0.5, 0.8, 0.9]
maxAmplifier = 5
```

</details>

Simplify weight list class to just a simple function handling a list of numbers.
[Weight List class](https://github.com/offbeat-stuff/Zombie-Apocalypse/blob/158359cd3229598a6b952e9f1856307330787e1e/src/main/java/io/github/offbeat_stuff/zombie_apocalypse/ProbabilityHandler.java#L50)

Currently it uses a extraWeights argument to fill the list for the number of elements.

So under the new implementation.
[1,20,30,40] for a size of 6 would result in

either [1,20,30,13,13,14] or [1,20,30,40,0,0]
based on a global config option.

Next.

Remove config options for material types for armor and tools.
Since they require more input from player side for config and are rather limited in their operation.

Next.

Join Armor and Tools(Weapons) into simply equipment config option.
